(function () {
    "use strict";

    angular
        .module("hubPortal")
        .controller("TransactionLookupCtrl",
            [
                "ProcessList",
                "ClientList",
                "TransactionTypeList",
                "TransactionQueryResource",
                "TransactionQueryBuilderService",
                TransactionLookupCtrl
            ]);

    function TransactionLookupCtrl(ProcessList, ClientList, TransactionTypeList, TransactionQueryResource, TransactionQueryBuilderService) {
        var vm = this;
        //vm.processList = ProcessList;
        //vm.clientList = ClientList;
        //vm.transactionTypeList = TransactionTypeList;

        vm.processList = [
            "1st Auto Name Search - Alliance ESL",
            "1st Auto Name Search - ESL",
            "1st Auto Policy Search - Alliance ESL",
            "1st Auto Policy Search - ESL",
            "1st Auto VIN Search - ESL",
            "1st Auto Vehicle Unit Number Search - ESL",
            "21st Century ClaimRegistration - ESL",
            "21st Century GetAutoHH",
            "21st Century GetAutoHH SV2 - Name Search",
            "21st Century GetAutoHH SV2 - Policy Search",
            "21st Century GetGlassTow",
            "21st Century HouseHold.Policies",
            "21st Century Long Pull Policy Search - ESL",
            "21st Century Name Search - ESL",
            "21st Century Policy Search - ESL",
            "21st Century Unsolicited Response",
            "21st Century VehiclePolicy Search - ESL",
            "AAA SEAGULL/WU ClaimRegistration Search - ESL",
            "AAA SEAGULL/WU HouseholdPolicy Search - ESL",
            "AAA SEAGULL/WU Name Search - ESL",
            "AAA SEAGULL/WU Policy Search - ESL",
            "AAA SEAGULL/WU VehiclePolicy Search - ESL",
            "AIG Name Search ESL",
            "AIG Policy Search ESL",
            "ARI Fleet Add Item - ESL",
            "ARI Fleet Claim Registration - ESL",
            "ARI Fleet Claim Status - ESL",
            "ARI Fleet Id Search - ESL",
            "ARI Fleet Policy Details - ESL",
            "ARI Fleet Request Approval - ESL",
            "ARI Fleet VIN Search - ESL",
            "ARMS Location Search - Alliance ESL",
            "ARMS Rental Reservation - FNOL",
            "ASI Add Contact - Alliance ESL",
            "ASI Claim Registration - Alliance ESL",
            "ASI Create Claim - Alliance ESL",
            "ASI Duplicate Check Search - Alliance ESL",
            "ASI Name Search - Alliance ESL",
            "ASI Phone Search - Alliance ESL",
            "ASI Policy Search - Alliance ESL",
            "ASI Update Claim - Alliance ESL",
            "ASI Update Mitigation - Alliance ESL",
            "AUTO CLUB (FL & GA) Claim Registration Web ESL",
            "AUTO CLUB (FL & GA) Name Search Web ESL",
            "AUTO CLUB (FL & GA) Policy Search Web ESL",
            "AUTO CLUB (FL & GA) Vehicle Lookup Web ESL",
            "Aaa South ClaimRegistration Search - Alliance ESL",
            "Aaa South ClaimRegistration Search ESL",
            "Aaa South Name File Search - Alliance ESL",
            "Aaa South Name File Search ESL",
            "Aaa South Name Search - Alliance ESL",
            "Aaa South Name Search ESL",
            "Aaa South Partial Policy Search - Alliance ESL",
            "Aaa South Partial Policy Search ESL",
            "Aaa South Policy File Search - Alliance ESL",
            "Aaa South Policy File Search ESL",
            "Aaa South Policy Search - Alliance ESL",
            "Aaa South Policy Search ESL",
            "Ace Invoice - ESL",
            "Ace Private Risk Claim Registration - Alliance ESL",
            "Ace Private Risk Invoice Remit ESL",
            "Ace Private Risk Invoice Remit Service Inbound Errors ESL",
            "Ace Private Risk Name Search - Alliance ESL",
            "Ace Private Risk Name Search ESL",
            "Ace Private Risk Partial Policy Search - Alliance ESL",
            "Ace Private Risk Partial Policy Search ESL",
            "Ace Private Risk Policy Search - Alliance ESL",
            "Ace Private Risk Policy Search ESL",
            "Adirondack Insurance FNOL Auto Loss - Alliance ESL",
            "Adirondack Insurance FNOL General Liability Loss - Alliance ESL",
            "Adirondack Insurance FNOL Property Loss - Alliance ESL",
            "Agri Business Name Search - Alliance ESL",
            "Agri Business Name Search - ESL",
            "Agri Business Policy Search - Alliance ESL",
            "Agri Business Policy Search - ESL",
            "Alfa Alliance Name Search - Alliance ESL",
            "Alfa Alliance Name Search ESL",
            "Alfa Alliance Policy Search - Alliance ESL",
            "Alfa Alliance Policy Search ESL",
            "Alfa Alliance Policy Workflow Search ESL",
            "Alfa Ins Claim Registration - ESL",
            "Alfa Ins Validate Claim Availability - ESL",
            "Alfa Name Search - ESL",
            "Alfa Policy Search",
            "Alfa Policy Search - ESL",
            "Alfa VIN Search - ESL",
            "Alfa Vision Duplicate Claim Search - Alliance ESL",
            "Alfa Vision FNOL Claim Registration - Alliance ESL",
            "Alfa Vision List - Alliance ESL",
            "Alfa Vision Name Search - Alliance ESL",
            "Alfa Vision Policy Search - Alliance ESL",
            "AllState Motor Club Name Search - ESL",
            "AllState Motor Club Policy Search - ESL",
            "Alliance File A Claim",
            "Allstate Claim Number Search ESL",
            "Allstate Claim Number WEB Search - ESL",
            "Allstate GHRN Claim Number Search ESL",
            "Allstate GHRN Claim Number WEB Search - ESL",
            "Allstate Name Search ESL",
            "Allstate Name WEB Search - ESL",
            "Allstate Partial Policy WEB Search - ESL",
            "Allstate Policy Search ESL",
            "Allstate Policy WEB Search - ESL",
            "Allstate Vehicle Policy Search ESL",
            "Allstate Vehicle Policy WEB Search - ESL",
            "Amazon Inbound Authorize IPN",
            "Amazon Inbound Capture IPN",
            "Amazon Inbound Heartbeat",
            "Amazon Inbound Order Reference IPN",
            "Amazon Inbound Refund IPN",
            "Amazon Payment Webscrape",
            "American Family Claim Registration ESL",
            "American Family Close Claim Registration - ESL",
            "American Family Commercial Search ESL",
            "American Family Connect Policy Search ESL",
            "American Family Name Search ESL",
            "American Family Phone Search ESL",
            "American Family Ping ESL",
            "American Family Policy Detail ESL",
            "American Family Policy Search ESL",
            "American Family Policy Search LU6.2 ESL",
            "American Family Reopen Claim - ESL",
            "American Family Rollout Status ESL",
            "American Family Update Claim Registration - ESL",
            "Amica Claim Registration - ESL",
            "Amica Id Search - ESL",
            "Amica Name Search - ESL",
            "Amica Policy Search - ESL",
            "Amica Update Claim - ESL",
            "Ariba Work Order Assignment",
            "Ariba Work Order Assignment ESL",
            "Ariba Work Order Assignment Ping ESL",
            "Aspen - CCC MOI - FNOL",
            "Aspen Claim Registration - ClaimsPro ESL",
            "Aspen Claim Registration - ESL",
            "Aspen Name Search - ClaimsPro ESL",
            "Aspen Name Search - ESL",
            "Aspen Policy Search - ClaimsPro ESL",
            "Aspen Policy Search - ESL",
            "Austin Mutual Name Search ESL",
            "Austin Mutual Policy Search ESL",
            "Austin Mutual VIN Search ESL",
            "Auto Club Group Check Request ESL",
            "Auto Club Group Claim Registration ESL",
            "Auto Club Group Claim Registration Web ESL",
            "Auto Club Group Name Search Inhouse ESL",
            "Auto Club Group Name Search MF ESL",
            "Auto Club Group Name Search Web ESL",
            "Auto Club Group Policy Search Inhouse ESL",
            "Auto Club Group Policy Search MF ESL",
            "Auto Club Group Policy Search Web ESL",
            "Auto Club Group Property Loss - Alliance ESL",
            "Auto Club Group Vehicle Lookup MF ESL",
            "Auto Club Group Vehicle Lookup Web ESL",
            "Auto Owners Corporation Policy Search MF ESL",
            "Berkley One Id Search - Alliance ESL",
            "Berkley One Id Search - ESL",
            "Berkley One Name Search - Alliance ESL",
            "Berkley One Name Search - ESL",
            "Berkley One Policy Search - Alliance ESL",
            "Berkley One Policy Search - ESL",
            "Best Price",
            "Best Price ESL",
            "Bristol West ClaimRegistration - ESL",
            "Bristol West GetAutoHH",
            "Bristol West GetAutoHH SV2 - Name Search",
            "Bristol West GetAutoHH SV2 - Policy Search",
            "Bristol West GetGlassTow",
            "Bristol West HouseHold.Policies",
            "Bristol West Long Pull Policy Search - ESL",
            "Bristol West Name Search - ESL",
            "Bristol West Policy Search - ESL",
            "Bristol West VehiclePolicy Search - ESL",
            "Buckeye Insurance Name Search ESL",
            "Buckeye Insurance Policy Search ESL",
            "CCCIS Appraisal Assign - Alliance ESL",
            "CCCIS Appraisal Search - Alliance ESL",
            "CCCIS MOI - Alliance ESL",
            "CNA Name Search - Alliance ESL",
            "CNA Policy Search - Alliance ESL",
            "CSAA Claim Registration",
            "CSAA Claim Registration ESL",
            "CSAA ClaimRegistration Auto - Alliance ESL",
            "CSAA ClaimRegistration Property - Alliance ESL",
            "CSAA Household Policy Search ESL",
            "CSAA HouseholdPolicy Search - Alliance ESL",
            "CSAA Name Search",
            "CSAA Name Search - Alliance ESL",
            "CSAA Name Search ESL",
            "CSAA Policy Search",
            "CSAA Policy Search - Alliance ESL",
            "CSAA Policy Search ESL",
            "CSAA PropertyPolicy Search - Alliance ESL",
            "CSAA Repair Network Search - Alliance ESL",
            "CSAA Vehicle Search ESL",
            "CSAA VehiclePolicy Search - Alliance ESL",
            "CSE Claim Registration - Alliance ESL",
            "CSE Claim Registration - ESL",
            "CSE General Liability Claim Registration - Alliance ESL",
            "CSE Name Search - Alliance ESL",
            "CSE Name Search - ESL",
            "CSE NameWeb Search - Alliance ESL",
            "CSE NameWeb Search - ESL",
            "CSE Policy Search - Alliance ESL",
            "CSE Policy Search - ESL",
            "CSE PolicyWeb Search - Alliance ESL",
            "CSE PolicyWeb Search - ESL",
            "CSE Property Claim Registration - Alliance ESL",
            "California Referral - Email",
            "California Referral - Load",
            "Central Mutual Callback Request ESL",
            "Central Mutual Claim Registration",
            "Central Mutual Claim Registration ESL",
            "Central Mutual Guardian Inbound Errors ESL",
            "Central Mutual Policy Search",
            "Central Mutual Policy Search ESL",
            "Central Mutual Shop Search ESL",
            "Chubb Canada Name Search - ESL",
            "Chubb Canada Policy Search - ESL",
            "Cincinnati Financial Billing Invoice",
            "Cincinnati Financial Billing Invoice - ESL",
            "Cincinnati Financial Billing Invoice Health Check",
            "Cincinnati Financial Billing Remittance",
            "Cincinnati Financial Billing Remittance - ESL",
            "Cincinnati Financial Billing Remittance Heartbeat - ESL",
            "Cincinnati Financial FNOL - Auto Loss",
            "Cincinnati Financial FNOL - Auto Loss ESL",
            "Cincinnati Financial FNOL - Property Loss",
            "Cincinnati Financial FNOL - Property Loss ESL",
            "Cincinnati Financial Policy Search ESL",
            "Citizens Insurance Claim Registration - Alliance ESL",
            "Citizens Insurance Name Search - ESL",
            "Citizens Insurance Partial Policy - ESL",
            "Citizens Insurance Partial Policy Search - Alliance ESL",
            "Citizens Insurance Partial Policy Search - ESL",
            "Citizens Insurance Policy - Alliance ESL",
            "Citizens Insurance Policy Search - Alliance ESL",
            "Citizens Insurance Policy Search - ESL",
            "Citizens Platinum Insurance Claim Registration - Alliance ESL",
            "Citizens Platinum Insurance Name Search - ESL",
            "Citizens Platinum Insurance Partial Policy Search - Alliance ESL",
            "Citizens Platinum Insurance Partial Policy Search - ESL",
            "Citizens Platinum Insurance Policy Search - Alliance ESL",
            "Citizens Platinum Insurance Policy Search - ESL",
            "Clearcover Policy Details - ESL",
            "Clearcover Policy Search - ESL",
            "Columbia Auto Claim Registration - Alliance ESL",
            "Columbia Claim Registration ESL",
            "Columbia Policy Search - Alliance ESL",
            "Columbia Policy Search ESL",
            "Columbia Property Claim Registration - Alliance ESL",
            "Columbia VIN Search ESL",
            "Columbia Vin Search - Alliance ESL",
            "Commercial LMAM Claim Registration - ESL",
            "Commercial LMAM ClientId Search - ESL",
            "Commercial LMAM Member Number Search - ESL",
            "Commercial LMAM Name Search - ESL",
            "Commercial LMAM PH Reimbursement ClientId Search - ESL",
            "Commercial LMAM PH Reimbursement Name Search - ESL",
            "Commercial LMAM PH Reimbursement Peril Search - ESL",
            "Commercial LMAM PH Reimbursement Policy Search - ESL",
            "Commercial LMAM Peril Search - ESL",
            "Commercial LMAM Policy Search - ESL",
            "Commercial LMAM Vehicle Policy Search - ESL",
            "Commercial LMAM-OHIO CASUALTY Claim Registration - ESL",
            "Commercial LMAM-OHIO CASUALTY ClientId Search - ESL",
            "Commercial LMAM-OHIO CASUALTY Member Number Search - ESL",
            "Commercial LMAM-OHIO CASUALTY Name Search - ESL",
            "Commercial LMAM-OHIO CASUALTY Peril Search - ESL",
            "Commercial LMAM-OHIO CASUALTY Policy Search - ESL",
            "Commercial LMAM-OHIO CASUALTY Vehicle Policy Search - ESL",
            "Commercial Liberty NorthW Claim Registration - ESL",
            "Commercial Liberty NorthW Name Search - ESL",
            "Commercial Liberty NorthW Policy Search - ESL",
            "Country Way Auto Loss Claim - FNOL",
            "Country Way Inhouse Name Search - FNOL",
            "Country Way Inhouse Policy Search - FNOL",
            "Country Way Inhouse Property Name Search - FNOL",
            "Country Way Inhouse Property Policy Search - FNOL",
            "Country Way NAME Search - ESL",
            "Country Way POLICY Search - ESL",
            "Country Way Policy Locator Member Search - ESL",
            "Country Way Policy Locator Member Search - FNOL",
            "Country Way Policy Locator Name Search - ESL",
            "Country Way Policy Locator Name Search - FNOL",
            "Country Way Policy Locator Policy Search - ESL",
            "Country Way Policy Locator Policy Search - FNOL",
            "Country Way Policy Locator Search - ESL",
            "Country Way Policy Search - FNOL",
            "Country Way PolicyWeb Search - ESL",
            "Country Way Property Loss Claim - FNOL",
            "Credit Card Auth",
            "Credit Card Create Token",
            "Credit Card Credit",
            "Credit Card Delete Token",
            "Credit Card ECHop",
            "Credit Card Find Token",
            "Credit Card Ping",
            "Credit Card Query ESL",
            "Credit Card Register Token",
            "Credit Card Reversal",
            "Credit Card SAHop",
            "Credit Card SGHop",
            "Credit Card Search",
            "Credit Card Settlement",
            "Css User Api - Add Contact By User",
            "Css User Api - Add Service Location By User",
            "Css User Api - Delete Accounts By User",
            "Css User Api - Delete Contact By Id",
            "Css User Api - Delete Service Location By Id",
            "Css User Api - Delete User Primary Contact/Location By Id",
            "Css User Api - Get Account Edits By Account",
            "Css User Api - Get Account Primary Service Location By User",
            "Css User Api - Get Accounts By User",
            "Css User Api - Get Contact By Id",
            "Css User Api - Get Contacts By User",
            "Css User Api - Get Service Location By Id",
            "Css User Api - Get Service Locations By User",
            "Css User Api - Get User By Id",
            "Css User Api - Get Users By Account",
            "Css User Api - Heartbeat",
            "Css User Api - Search Fleet",
            "Css User Api - Unknown",
            "Css User Api - Update Account Primary Service Location By User",
            "Css User Api - Update Accounts By User",
            "Css User Api - Update Contact By Id",
            "Css User Api - Update Service Location By Id",
            "Css User Api - Update User By Id",
            "DB Updater",
            "DB Updater - ESL",
            "DB Updater Heartbeat - ESL",
            "DUMMY - Delete",
            "Donegal Partial Policy Search - Alliance ESL",
            "Donegal Policy Search - Alliance ESL",
            "Donegal Policy Search ESL",
            "Duncan RV Transfer ESL",
            "EMC Claim Registration - Alliance ESL",
            "EMC Name Search - Alliance ESL",
            "EMC Name Search ESL",
            "EMC Policy Search - Alliance ESL",
            "EMC Policy Search ESL",
            "Elephant Claim Registration - ESL",
            "Elephant Name Search - ESL",
            "Elephant Policy Search - ESL",
            "Email Monitor",
            "Email Store and Forward",
            "Emailer",
            "Emailer - Automated Reminder",
            "Emailer - Inshop Appointment Reminder",
            "Emailer - Inshop Appointment Reminder SV2 Doc Save",
            "Emailer - Mobile Appointment Reminder",
            "Emailer - Mobile Appointment Reminder SV2 Doc Save",
            "Emailer - Pre Auth Receipt",
            "Emailer - Pre Auth Receipt Giant",
            "Emailer - Receipt",
            "Emailer - Receipt Giant",
            "Emailer - Recovery Survey",
            "Emailer - Safelite Complaint Gift",
            "Emailer - Safelite Progressive Survey Invite",
            "Emailer - Safelite Survey Invite",
            "Emailer - Third Party Progressive Survey Invite",
            "Emailer - Third Party Survey Invite",
            "Emkay Canada VIN Search - ESL",
            "Emkay Canada Vehicle Unit Number Search - ESL",
            "Emkay VIN Search - ESL",
            "Emkay Vehicle Unit Number Search - ESL",
            "Encompass Name Search - Alliance ESL",
            "Encompass Name Search - ESL",
            "Encompass Name WEB Search - ESL",
            "Encompass Partial Policy WEB Search - ESL",
            "Encompass Policy Search - Alliance ESL",
            "Encompass Policy Search - ESL",
            "Encompass Policy WEB Search - ESL",
            "Encompass VIN Search - Alliance ESL",
            "Encompass VIN Search - ESL",
            "Encompass Vehicle Unit Number Search - Alliance ESL",
            "Encompass Vehicle Unit Number Search - ESL",
            "Energi Name Search Inhouse ESL",
            "Energi Policy Search Inhouse ESL",
            "Energi VIN Search ESL",
            "Enumclaw Name Search - ESL",
            "Enumclaw Policy Search - ESL",
            "Erie Claim Registration - ESL",
            "Erie Name Search - ESL",
            "Erie Policy Search - ESL",
            "Erie Policy Search LU6.2 ESL",
            "Esurance Canada Name Search - ESL",
            "Esurance Canada Policy Search - ESL",
            "Esurance Name Search - ESL",
            "Esurance Name Web Search - ESL",
            "Esurance Policy Search - ESL",
            "Esurance Policy Web Search - ESL",
            "Explorer ClaimRegistration Auto - Alliance ESL",
            "Explorer Duplicate Claim Check - Alliance ESL",
            "FCA Company Cars Policy Search - ESL",
            "FCA Company Cars VIN Search - ESL",
            "FEDEX EXPRESS Invoice - ESL",
            "Farmers ClaimRegistration - ESL",
            "Farmers FNOL - GlassClaim",
            "Farmers GetAutoHH",
            "Farmers GetAutoHH EB2B - Name Search",
            "Farmers GetAutoHH EB2B - Policy Search",
            "Farmers GetAutoHH SV2 - Name Search",
            "Farmers GetAutoHH SV2 - Policy Search",
            "Farmers GetGlassTow",
            "Farmers HouseHold.Policies",
            "Farmers Long Pull Policy Search - ESL",
            "Farmers Name Search - ESL",
            "Farmers Policy Search - ESL",
            "Farmers RV Transfer ESL",
            "Farmers Unsolicited Response",
            "Farmers Unsolicited Response - ESL",
            "Farmers Unsolicited Response Ping - ESL",
            "Farmers VehiclePolicy Search - ESL",
            "Financial File Not Received",
            "Florida Specialty Claim Registration - FNOL",
            "Florida Specialty Policy Search - FNOL",
            "Foremost Motorhome ClaimRegistration - ESL",
            "Foremost Motorhome Long Pull Policy Search ESL",
            "Foremost Motorhome Name Search - ESL",
            "Foremost Motorhome Policy Search - ESL",
            "Foremost Motorhome VehiclePolicy Search - ESL",
            "Fremont Insurance Partial Policy Search - Alliance ESL",
            "Fremont Insurance Partial Policy Search - ESL",
            "Fremont Insurance Policy Search - Alliance ESL",
            "Fremont Insurance Policy Search - ESL",
            "GEICO Loss Notification",
            "Geico Claim Registration ESL",
            "Geico Phone Search ESL",
            "Geico Policy Search ESL",
            "Geico Save Claim ESL",
            "Geocode Service",
            "Georgia Farm Bureau Claim Adjuster Code MF - Alliance ESL",
            "Georgia Farm Bureau Claim Registration - Alliance ESL",
            "Georgia Farm Bureau Claim Registration - FNOL",
            "Georgia Farm Bureau Claim Registration ESL",
            "Georgia Farm Bureau Claim Registration MF - Alliance ESL",
            "Georgia Farm Bureau Claim Registration MF ESL",
            "Georgia Farm Bureau Claim RegistrationWeb - Alliance ESL",
            "Georgia Farm Bureau Claim RegistrationWeb ESL",
            "Georgia Farm Bureau Duplicate Claim Search - Alliance ESL",
            "Georgia Farm Bureau Duplicate Claim Search - FNOL",
            "Georgia Farm Bureau Member Search MF - Alliance ESL",
            "Georgia Farm Bureau Member Search MF ESL",
            "Georgia Farm Bureau Name Search MF - Alliance ESL",
            "Georgia Farm Bureau Name Search MF ESL",
            "Georgia Farm Bureau Partial Policy Search - Alliance ESL",
            "Georgia Farm Bureau Partial Policy Search - FNOL",
            "Georgia Farm Bureau Partial Policy Search ESL",
            "Georgia Farm Bureau Partial PolicyCL Search - Alliance ESL",
            "Georgia Farm Bureau Partial PolicyCL Search - FNOL",
            "Georgia Farm Bureau Partial PolicyCL Search ESL",
            "Georgia Farm Bureau Partial PolicyCL2 Search - Alliance ESL",
            "Georgia Farm Bureau Partial PolicyCL2 Search ESL",
            "Georgia Farm Bureau Partial PolicyCLWeb Search ESL",
            "Georgia Farm Bureau Partial PolicyWeb Search - Alliance ESL",
            "Georgia Farm Bureau Partial PolicyWeb Search ESL",
            "Georgia Farm Bureau Password Change MF ESL",
            "Georgia Farm Bureau Policy Search - Alliance ESL",
            "Georgia Farm Bureau Policy Search - FNOL",
            "Georgia Farm Bureau Policy Search ESL",
            "Georgia Farm Bureau Policy Search MF - Alliance ESL",
            "Georgia Farm Bureau Policy Search MF ESL",
            "Georgia Farm Bureau PolicyCL Search - Alliance ESL",
            "Georgia Farm Bureau PolicyCL Search - FNOL",
            "Georgia Farm Bureau PolicyCL Search ESL",
            "Georgia Farm Bureau PolicyCL2 Search - Alliance ESL",
            "Georgia Farm Bureau PolicyCL2 Search ESL",
            "Georgia Farm Bureau PolicyCLWeb Search ESL",
            "Georgia Farm Bureau PolicyWeb Search - Alliance ESL",
            "Georgia Farm Bureau PolicyWeb Search ESL",
            "Germania Claim Registration",
            "Germania Claim Registration ESL",
            "Germania ClaimRegistration Alliance ESL",
            "Germania ClaimRegistration Web ESL",
            "Germania Name Search",
            "Germania Name Search Alliance ESL",
            "Germania Name Search ESL",
            "Germania Policy Search",
            "Germania Policy Search Alliance ESL",
            "Germania Policy Search ESL",
            "Germania Property Loss Alliance ESL",
            "GlassClaim File-A-Claim",
            "GlassClaim Website Allstate Web-to-web Connection",
            "GlassClaim Website Cancel",
            "GlassClaim Website FNOL Submit",
            "GlassClaim Website GEICO Web-to-web Connection",
            "GlassClaim Website Pricing",
            "GlassClaim Website Scheduling",
            "GlassClaim Website WorkOrderManagement",
            "Goodville Auto Loss - Alliance ESL",
            "Goodville ClaimRegistration - ESL",
            "Goodville Policy Search - Alliance ESL",
            "Goodville Policy Search - ESL",
            "Goodville Property Loss - Alliance ESL",
            "Grain Dealers Name Search - Alliance ESL",
            "Grain Dealers Name Search ESL",
            "Grain Dealers Partial Policy Search - Alliance ESL",
            "Grain Dealers Partial Policy Search ESL",
            "Grain Dealers Policy Search - Alliance ESL",
            "Grain Dealers Policy Search ESL",
            "Grange Insurance Association Policy Search - Alliance ESL",
            "Grange Insurance Association Policy Search ESL",
            "Grange Insurance Claim Registration - Alliance ESL",
            "Grange Insurance Claim Registration - ESL",
            "Grange Insurance Company Search - Alliance ESL",
            "Grange Insurance Company Search - ESL",
            "Grange Insurance Duplicate Search - Alliance ESL",
            "Grange Insurance Duplicate Search - ESL",
            "Grange Insurance Name Search - Alliance ESL",
            "Grange Insurance Name Search - ESL",
            "Grange Insurance Phone Search - Alliance ESL",
            "Grange Insurance Phone Search - ESL",
            "Grange Insurance Policy Details - Alliance ESL",
            "Grange Insurance Policy Details - ESL",
            "Grange Insurance Policy Search - Alliance ESL",
            "Grange Insurance Policy Search - ESL",
            "Grange Mutual Claim Registration ESL",
            "Grange Mutual Duplicate Claim Check ESL",
            "Grange Mutual Name Search ESL",
            "Grange Mutual Policy Search ESL",
            "Grange Mutual Referral",
            "Grinnell Claim Registration ESL (Web Scrape)",
            "Grinnell Claim Registration Web Search - Alliance ESL",
            "Grinnell Claim Registration Web Search - ESL",
            "Grinnell FNOL Registration (Web Scrape) - Alliance ESL",
            "Grinnell Name Search - Alliance ESL",
            "Grinnell Name Search ESL",
            "Grinnell Policy Search - Alliance ESL",
            "Grinnell Policy Search ESL",
            "Grinnell Registration ESL",
            "Guardian Insurance Callback Request ESL",
            "Guardian Insurance Service Inbound Errors ESL",
            "Guardian Insurance Service Ping ESL",
            "Guardian Service Inbound Errors ESL",
            "Guardian Service Ping ESL",
            "Guide One Claim Registration ESL",
            "Guide One Policy Search - Alliance ESL",
            "Guide One Policy Search ESL",
            "Guidewire Internal Claim Registration Alliance ESL",
            "Guidewire Internal Claim Registration ESL",
            "Guidewire Internal Duplicate Check Alliance ESL",
            "Guidewire Internal Duplicate Check ESL",
            "Hanover - CCC Appraisal Assign - Alliance ESL",
            "Hanover - CCC Appraisal Search - Alliance ESL",
            "Hanover Insurance Claim Registration - Alliance ESL",
            "Hanover Insurance Name Search - ESL",
            "Hanover Insurance Partial Policy Search - Alliance ESL",
            "Hanover Insurance Partial Policy Search - ESL",
            "Hanover Insurance Policy Search - Alliance ESL",
            "Hanover Insurance Policy Search - ESL",
            "Hanover Insurance Policy Web Search - Alliance ESL",
            "Hanover Platinum Insurance Name Search - ESL",
            "Hanover Platinum Insurance Partial Policy Search - Alliance ESL",
            "Hanover Platinum Insurance Partial Policy Search - ESL",
            "Hanover Platinum Insurance Policy Search - ESL",
            "Hartford - PolicyInquiry",
            "Hartford Policy Search ESL",
            "Haulers Claim Registration - Alliance ESL",
            "Haulers Claim Registration ESL",
            "Haulers Policy Search - Alliance ESL",
            "Haulers Policy Search ESL",
            "Homesite Claim Registration Property - Alliance ESL",
            "Homesite Claim Search - Alliance ESL",
            "Homesite Name Search - Alliance ESL",
            "Homesite Phone Search - Alliance ESL",
            "Homesite Policy Search - Alliance ESL",
            "Hop Lite Ping",
            "Horace Mann - CCC Appraisal Assign - Alliance ESL",
            "Horace Mann - CCC Appraisal Search - Alliance ESL",
            "Horace Mann - CCC MOI - Alliance ESL",
            "Horace Mann Adjuster List Search - Alliance ESL",
            "Horace Mann Auto Loss - Alliance ESL",
            "Horace Mann Auto Loss GW - Alliance ESL",
            "Horace Mann Cat Code List Search - Alliance ESL",
            "Horace Mann Claim History Search - Alliance ESL",
            "Horace Mann Claim History Search - ESL",
            "Horace Mann Claim History Search GW - Alliance ESL",
            "Horace Mann Claim History Search GW - ESL",
            "Horace Mann Claim Registration - ESL",
            "Horace Mann Claim Registration GW - ESL",
            "Horace Mann Claim Type List Search - Alliance ESL",
            "Horace Mann Client Number Search - Alliance ESL",
            "Horace Mann Client Number Search - ESL",
            "Horace Mann Client Number Search GW - Alliance ESL",
            "Horace Mann Client Number Search GW - ESL",
            "Horace Mann Coverage Types List Search - Alliance ESL",
            "Horace Mann Damage List Search - Alliance ESL",
            "Horace Mann Drp Shop List Search - Alliance ESL",
            "Horace Mann FNOL - Alliance ESL",
            "Horace Mann Injury List Search - Alliance ESL",
            "Horace Mann Lob List Search - Alliance ESL",
            "Horace Mann Location Names List Search - Alliance ESL",
            "Horace Mann Name Policy Search ESL",
            "Horace Mann Name Search - Alliance ESL",
            "Horace Mann Name Search - ESL",
            "Horace Mann Name Search ESL",
            "Horace Mann Name Search GW - Alliance ESL",
            "Horace Mann Name Search GW - ESL",
            "Horace Mann Policy Search - Alliance ESL",
            "Horace Mann Policy Search - ESL",
            "Horace Mann Policy Search ESL",
            "Horace Mann Policy Search GW - Alliance ESL",
            "Horace Mann Policy Search GW - ESL",
            "Horace Mann Property Loss - Alliance ESL",
            "Horace Mann Property Loss GW - Alliance ESL",
            "Horace Mann Role Category List Search - Alliance ESL",
            "Horace Mann Role Types List Search - Alliance ESL",
            "Horace Mann Unit Data Types List Search - Alliance ESL",
            "Horace Mann Unit Sub Types List Search - Alliance ESL",
            "Horace Mann Unit Type List Search - Alliance ESL",
            "Horace Mann VIN Search ESL",
            "Houston General FNOL Auto Loss - Alliance ESL",
            "Houston General FNOL General Liability Loss - Alliance ESL",
            "Houston General FNOL Property Loss - Alliance ESL",
            "Human Resources Lookup - Department",
            "Human Resources Lookup - Employee",
            "Human Resources Update - DW",
            "Human Resources Update - Oracle",
            "Human Resources Update - Safelite U",
            "IAA Assignment Detail - ESL",
            "IAA Assignment Release - ESL",
            "IAA Assignment Update - ESL",
            "IAA Notes Add - ESL",
            "IAA Storage Location Add - ESL",
            "IAA Storage Location Details - ESL",
            "IAA Storage Location Search - ESL",
            "IAA Storage Location Update - ESL",
            "IMT Policy Search - Alliance ESL",
            "IMT Policy Search ESL",
            "Idaho Farm Bureau Claim Registration ESL",
            "Idaho Farm Bureau Name Search ESL",
            "Idaho Farm Bureau Policy Search ESL",
            "Indiana Farm Bureau Callback Request ESL",
            "Indiana Farm Bureau Claim Registration ESL",
            "Indiana Farm Bureau Guardian Inbound Errors ESL",
            "Indiana Farm Bureau Shop Search ESL",
            "Indiana Farmers FNOL - Auto Loss ESL",
            "Indiana Farmers FNOL - Property Loss ESL",
            "Invoice Remit Service Inbound Errors ESL",
            "Invoice Remit Service Ping ESL",
            "Iowa Farm Bureau Name Web Search - Alliance ESL",
            "Iowa Farm Bureau Name Web Search ESL",
            "Iowa Farm Bureau Partial Policy Search - Alliance ESL",
            "Iowa Farm Bureau Partial Policy Search ESL",
            "Iowa Farm Bureau Policy Search - Alliance ESL",
            "Iowa Farm Bureau Policy Search ESL",
            "Iowa Farm Bureau Policy Web Search - Alliance ESL",
            "Iowa Farm Bureau Policy Web Search ESL",
            "Kemper Claim Registration - Alliance ESL",
            "Kemper Name Search - Alliance ESL",
            "Kemper Name Search - ESL",
            "Kemper Partial Policy Search - Alliance ESL",
            "Kemper Partial Policy Search - ESL",
            "Kemper Policy Search - Alliance ESL",
            "Kemper Policy Search - ESL",
            "Kemper Preferred Name Search - ESL",
            "Kemper Preferred Partial Policy Search - ESL",
            "Kemper Preferred Policy Search - ESL",
            "LMAM Claim Registration ESL",
            "LMAM Client Id Search",
            "LMAM ClientId Search - ESL",
            "LMAM Name Search",
            "LMAM Name Search - ESL",
            "LMAM Name Search ESL",
            "LMAM PH Reimbursement ClientId Search - ESL",
            "LMAM PH Reimbursement Name Search - ESL",
            "LMAM PH Reimbursement Peril Search - ESL",
            "LMAM PH Reimbursement Policy Search - ESL",
            "LMAM Peril Search",
            "LMAM Peril Search - ESL",
            "LMAM Policy Search",
            "LMAM Policy Search - ESL",
            "LMAM Policy Search ESL",
            "LMAM-OHIO CASUALTY ClientId Search - ESL",
            "LMAM-OHIO CASUALTY Name Search - ESL",
            "LMAM-OHIO CASUALTY Peril Search - ESL",
            "LMAM-OHIO CASUALTY Policy Search - ESL",
            "LeMars Insurance Partial Policy Search - Alliance ESL",
            "LeMars Insurance Policy Search - Alliance ESL",
            "LeMars Insurance Policy Search ESL",
            "Lease Plan Claim Registration - ESL",
            "Lease Plan Client List - ESL",
            "Lease Plan Update Schedule - ESL",
            "Lease Plan VIN Search - ESL",
            "LeasePlan VIN Search",
            "Legacy Insurance Claim Registration - Alliance ESL",
            "Legacy Insurance Name Search - Alliance ESL",
            "Legacy Insurance Partial Policy Search - Alliance ESL",
            "Legacy Insurance Policy Search - Alliance ESL",
            "Liberty Mutual Adjuster Assignment - ClaimsPro ESL",
            "Liberty Mutual Appraisal Assignment - ClaimsPro ESL",
            "Liberty Mutual Appraisal Search - ClaimsPro ESL",
            "Liberty Mutual Claim History - ClaimsPro ESL",
            "Liberty Mutual Claim Registration - ClaimsPro ESL",
            "Liberty Mutual Claim Registration ESL",
            "Liberty Mutual Household Policy Search ESL",
            "Liberty Mutual NAMEFILE Search - ESL",
            "Liberty Mutual Name Search - ClaimsPro ESL",
            "Liberty Mutual Name Search ESL",
            "Liberty Mutual POLICYFILE Search - ESL",
            "Liberty Mutual Phone Search - ClaimsPro ESL",
            "Liberty Mutual Policy Details Search - ClaimsPro ESL",
            "Liberty Mutual Policy Search - ClaimsPro ESL",
            "Liberty Mutual Policy Search ESL",
            "Liberty Unsolicited Response",
            "MEEMIC Name Search ESL",
            "MEEMIC Partial Policy Search ESL",
            "MEEMIC Policy Search ESL",
            "MID ATLANTIC GROUP AAA ClaimRegistration Search - ESL",
            "MID ATLANTIC GROUP AAA HouseholdPolicy Search - ESL",
            "MID ATLANTIC GROUP AAA Name Search - ESL",
            "MID ATLANTIC GROUP AAA Policy Search - ESL",
            "MID ATLANTIC GROUP AAA VehiclePolicy Search - ESL",
            "Maine Mutual Group Name Search - Alliance ESL",
            "Maine Mutual Group Name Search - ESL",
            "Maine Mutual Group Partial Policy Search - Alliance ESL",
            "Maine Mutual Group Partial Policy Search - ESL",
            "Maine Mutual Group Policy Search - Alliance ESL",
            "Maine Mutual Group Policy Search - ESL",
            "Map Wheels Name Search - ESL",
            "Map Wheels Policy Search - ESL",
            "Map Wheels Vin Search - ESL",
            "Mapfre Policy Search - ESL",
            "Meemic Claim Registration ESL",
            "Mendota Insurance Auto Loss - Alliance ESL",
            "Merchants FNOL Claim Registration - Alliance ESL",
            "Merchants Name Search - Alliance ESL",
            "Merchants Name Search ESL",
            "Merchants Policy Search - Alliance ESL",
            "Merchants Policy Search ESL",
            "Messaging Gateway Health Check",
            "Messaging Gateway Send Scripted Text Message",
            "Messaging Gateway Send Text Message",
            "Messaging Gateway Status Query",
            "Met Life Claim Create via SV2",
            "Met Life Claim Registration - ESL",
            "Met Life Policy Search - ESL",
            "Met Life Policy Search via SV2",
            "Met Life Service Claim Registration - ESL",
            "Met Life Service Name Search - ESL",
            "Met Life Service Policy Search - ESL",
            "Metromile Claim Create - Alliance ESL",
            "Metromile Claim Registration - Alliance ESL",
            "Metromile Claim Registration ESL",
            "Metromile Name Search Inhouse - Alliance ESL",
            "Metromile Name Search Inhouse ESL",
            "Metromile Name Web Search - Alliance ESL",
            "Metromile Name Web Search ESL",
            "Metromile Policy Search Inhouse - Alliance ESL",
            "Metromile Policy Search Inhouse ESL",
            "Metromile Policy Web Search - Alliance ESL",
            "Metromile Policy Web Search ESL",
            "Michigan Insurance Partial Policy Search - Alliance ESL",
            "Michigan Insurance Policy Search - Alliance ESL",
            "Michigan Insurance Policy Search ESL",
            "Motorists Group Auto Loss - Alliance ESL",
            "Motorists Group FNOL - Auto Loss",
            "Motorists Group FNOL - Auto Loss - ESL",
            "Motorists Group FNOL - Property Loss",
            "Motorists Group FNOL - Property Loss - ESL",
            "Motorists Group General Liability Loss - Alliance ESL",
            "Motorists Group Policy Search ESL",
            "Motorists Group Property Loss - Alliance ESL",
            "Motorists Group Rental Location - Alliance ESL",
            "Motorists Group Workers Comp Loss - Alliance ESL",
            "Motorists Insurance Claim Registration ESL",
            "Motorists Insurance Name Search ESL",
            "Motorists Insurance Policy Search ESL",
            "Mutual Benefit Group Name Search - Alliance ESL",
            "Mutual Benefit Group Name Search ESL",
            "Mutual Benefit Group Policy Search - Alliance ESL",
            "Mutual Benefit Group Policy Search ESL",
            "NGIC Name Search - ESL",
            "NGIC Phone Search - ESL",
            "NGIC Policy Details - ESL",
            "NGIC Policy Search - ESL",
            "NGIC VIN Search  - ESL",
            "NJ Skylands FNOL Auto Loss - Alliance ESL",
            "NJ Skylands FNOL General Liability Loss - Alliance ESL",
            "NJ Skylands FNOL Property Loss - Alliance ESL",
            "NJM ClaimRegistration - Alliance ESL",
            "NJM ClaimRegistration Inbound - Alliance ESL",
            "NJM ClaimRegistration Inbound Search ESL",
            "NJM ClaimRegistration Search ESL",
            "NJM Policy Search - Alliance ESL",
            "NJM Policy Search - ESL",
            "Nationwide ClaimRegistration Search - ESL",
            "Nationwide Household Policy Search - ESL",
            "Nationwide Inbound FNOL",
            "Nationwide Name Search - ESL",
            "Nationwide Policy Search - ESL",
            "North Star Name Search - Alliance ESL",
            "North Star Name Search ESL",
            "North Star Policy Search - Alliance ESL",
            "North Star Policy Search ESL",
            "Northern Neck Name Search - ESL",
            "Northern Neck Name Search - FNOL",
            "Northern Neck Policy Search - ESL",
            "Northern Neck Policy Search - FNOL",
            "Northern Neck Property Name Search - FNOL",
            "Northern Neck Property Policy Search - FNOL",
            "Ohio Casualty Commercial Claim Registration ESL",
            "Ohio Casualty Commercial Name Search ESL",
            "Ohio Casualty Commercial Policy Search ESL",
            "Ohio Mutual Claim Registration - Alliance ESL",
            "Ohio Mutual Claim Registration - ESL",
            "Ohio Mutual Name Search - Alliance ESL",
            "Ohio Mutual Name Search - ESL",
            "Ohio Mutual Policy Search - Alliance ESL",
            "Ohio Mutual Policy Search - ESL",
            "Ohio Mutual Rental Location - Alliance ESL",
            "One Beacon FNOL - Auto Loss",
            "One Beacon FNOL - Auto Loss ESL",
            "One Beacon FNOL - General Liability",
            "One Beacon FNOL - General Liability ESL",
            "One Beacon FNOL - Load",
            "One Beacon FNOL - Property Loss",
            "One Beacon FNOL - Property Loss ESL",
            "One Beacon FNOL - Workers Comp Loss ESL",
            "One Beacon Name Search",
            "One Beacon Name Search ESL",
            "One Beacon Policy Search",
            "One Beacon Policy Search ESL",
            "PHH Service Card Search - ESL",
            "PHH VIN Search - ESL",
            "PHH lookup",
            "PO Receipt",
            "Payment Application HopLite",
            "Payment Application SafeliteHop",
            "Payment Service AzAmazonExpress Auth",
            "Payment Service AzAmazonExpress Capture",
            "Payment Service AzAmazonExpress Credit",
            "Payment Service AzAmazonExpress Credit Update",
            "Payment Service AzAmazonExpress OrderInit",
            "Payment Service AzAmazonExpress OrderSetup",
            "Payment Service AzAmazonExpress Query",
            "Payment Service AzAmazonExpress Reversal",
            "Payment Service AzAmazonExpress UnitCase",
            "Payment Service CsCreditCard Auth",
            "Payment Service CsCreditCard Capture",
            "Payment Service CsCreditCard CreateToken",
            "Payment Service CsCreditCard Credit",
            "Payment Service CsCreditCard DeleteToken",
            "Payment Service CsCreditCard FindToken",
            "Payment Service CsCreditCard Query",
            "Payment Service CsCreditCard RegToken",
            "Payment Service CsCreditCard Reversal",
            "Payment Service CsCreditCard Search",
            "Payment Service CsCreditCard TokenPurge",
            "Payment Service CsPayPal Auth",
            "Payment Service CsPayPal Capture",
            "Payment Service CsPayPal Credit",
            "Payment Service CsPayPal EcGetDetails",
            "Payment Service CsPayPal EcOrderSetup",
            "Payment Service CsPayPal EcSet",
            "Payment Service CsPayPal Query",
            "Payment Service CsPayPal Reversal",
            "Payment Service Ping",
            "Payment Service Status - ESL",
            "Payment Service Status Admin - ESL",
            "Payment Service Status Ping - ESL",
            "Payment Service Status Switch - ESL",
            "Payment Service Unknown",
            "Payment Services CyberSource CreditCard UnitCase",
            "Pci Payment Service CsCreditCard Auth",
            "Pci Payment Service Ping",
            "Pci Payment Service Unknown",
            "Pekin Insurance Claim History - Alliance ESL",
            "Pekin Insurance Claim Registration - Alliance ESL",
            "Pekin Insurance Name Search - Alliance ESL",
            "Pekin Insurance Name Search - ESL",
            "Pekin Insurance Policy Search - Alliance ESL",
            "Pekin Insurance Policy Search - ESL",
            "Pekin Name Search - Alliance ESL",
            "Pekin Name Search ESL",
            "Pekin Partial Policy Search - Alliance ESL",
            "Pekin Partial Policy Search ESL",
            "Pekin Policy Search - Alliance ESL",
            "Pekin Policy Search ESL",
            "Peninsula Partial Policy Search - Alliance ESL",
            "Peninsula Policy Search - Alliance ESL",
            "Peninsula Policy Search ESL",
            "Penn National Name Search - Alliance ESL",
            "Penn National Name Search ESL",
            "Penn National Policy Search - Alliance ESL",
            "Penn National Policy Search ESL",
            "Penn National Property Name Search - Alliance ESL",
            "Penn National Property Policy Search - Alliance ESL",
            "Penn National Rental Location - Alliance ESL",
            "Portage la Prairie Canada Name Search - ESL",
            "Portage la Prairie Canada Policy Search - ESL",
            "Preferred Mutual Auto Loss - Alliance ESL",
            "Preferred Mutual Auto Ping - Alliance ESL",
            "Preferred Mutual Property Loss - Alliance ESL",
            "Preferred Mutual Property Ping - Alliance ESL",
            "Progressive Claim Registration - ESL",
            "Progressive Company Search - ESL",
            "Progressive Duncan RV Transfer",
            "Progressive Name Search - ESL",
            "Progressive Phone Search - ESL",
            "Progressive Policy Search - ESL",
            "Progressive VIN Search - ESL",
            "Pure Name Search - ESL",
            "Pure Policy Search - ESL",
            "QBE Insurance Name Search - ESL",
            "QBE Insurance Partial Policy Search - ESL",
            "QBE Insurance Policy Search - ESL",
            "Quincy Mutual - CCC Appraisal Assign - Alliance ESL",
            "Quincy Mutual - CCC Appraisal Search - Alliance ESL",
            "Quincy Mutual - CCC MOI - Alliance ESL",
            "Quincy Name Search - Alliance FNOL",
            "Quincy Policy Search - Alliance FNOL",
            "Reliant General Claim Registration - Alliance FNOL",
            "Reliant General Name Search - Alliance FNOL",
            "Reliant General Policy Search - Alliance FNOL",
            "Root Insurance Claim Registration - Alliance ESL",
            "Root Insurance Claim Registration - ESL",
            "Root Insurance Name Search - Alliance ESL",
            "Root Insurance Name Search - ESL",
            "Root Insurance Policy Search - Alliance ESL",
            "Root Insurance Policy Search - ESL",
            "SAG Account Info - Web",
            "SAG Account Management - Web",
            "SAG Account Management : Add - Web",
            "SAG Account Management : Delete - Web",
            "SAG Add Address - Web",
            "SAG Buyout Request Email - Web",
            "SAG Credit Hold Override",
            "SAG Delivery Schedules - Web",
            "SAG Delivery Time - Web",
            "SAG EON - Web",
            "SAG Fees - Web",
            "SAG Interchangeable Parts - Web",
            "SAG Mainframe MQ - Web",
            "SAG New User - Web",
            "SAG Order Return - Web",
            "SAG Part Search - Web",
            "SAG Part to Vehicle Search - Web",
            "SAG Promotion Apply - Web",
            "SAG Promotion GetInfo - Web",
            "SAG Promotion Search - Web",
            "SAG Promotion Validate - Web",
            "SAG Related Part Search - Web",
            "SAG Return Email - Web",
            "SAG Supply Search - Web",
            "SAG Token Management : Add - Web",
            "SAG Token Management : Delete - Web",
            "SAG Token Management : Get - Web",
            "SAG Valid User - Web",
            "SAG Vehicle Id - Web",
            "SAG Vehicle Makes - Web",
            "SAG Vehicle Models - Web",
            "SAG Vehicle Part Search - Web",
            "SAG Vehicle Styles - Web",
            "SAG Vehicle Years - Web",
            "SAG Wholesale Order Updates - Web",
            "SAG Wholesale Orders - Web",
            "SAY Claim Registration - Alliance ESL",
            "SAY Claim Submission - Alliance ESL",
            "SAY Decrypt Policy Number - Alliance ESL",
            "SAY Name Search - Alliance ESL",
            "SAY Name Web Search - Alliance ESL",
            "SAY Policy Search - Alliance ESL",
            "SAY Policy Web Search - Alliance ESL",
            "SGCNetwork Fax Request for Referrals - Web",
            "SGCNetwork Invoices - Web",
            "SGCNetwork Void Referrals - Web",
            "SMS Inbound - ESL",
            "SMS Inbound Heartbeat",
            "SMS Outbound - ESL",
            "SMS Outbound Heartbeat",
            "SMS Status - ESL",
            "SafeCo Claim Registration",
            "SafeCo Claim Registration - ESL",
            "SafeCo Duplicate Search",
            "SafeCo Duplicate Search - ESL",
            "SafeCo Household Policy Search - ESL",
            "SafeCo Name Search",
            "SafeCo Name Search - ESL",
            "SafeCo Policy Search",
            "SafeCo Policy Search - ESL",
            "Safelite Promotions Process Info Inquiry Search - Alliance ESL",
            "Safelite Promotions Process Info Inquiry Search - ESL",
            "Safelite Website FNOL Submit",
            "Safelite Website Geocode",
            "Safelite Website Insurance Account Management",
            "Safelite Website MCM",
            "Safelite Website Market Job Data",
            "Safelite Website Parts",
            "Safelite Website Pricing",
            "Safelite Website Promotions",
            "Safelite Website SalesTax",
            "Safelite Website Scheduling",
            "Safelite Website Vehicle",
            "Safelite Website Vehicle Years",
            "Safelite.com Agent Callback Request",
            "Safelite.com Customer Callback Request",
            "Safelite.com FNOL Submit",
            "Safelite.com Pricing",
            "Safelite.com Promotions",
            "Safelite.com Scheduling",
            "Secura Name Search - ESL",
            "Secura Policy Search - ESL",
            "Security First Cat Code List Search - Alliance ESL",
            "Security First Claim Registration - Alliance ESL",
            "Security First Claim Search - Alliance ESL",
            "Security First Claim Type Search - Alliance ESL",
            "Security First Duplicate Claim Check - Alliance ESL",
            "Security First General Liability Loss - Alliance ESL",
            "Security First Name Search - Alliance ESL",
            "Security First Policy Search - Alliance ESL",
            "Security First Preferred Providers - Alliance ESL",
            "Security First Provider Jobs - Alliance ESL",
            "Selective Claim and Loss Detail - ESL",
            "Selective Policy Search",
            "Selective Policy Search - ESL",
            "ServiceAutoGlass WTS - Web",
            "ServiceAutoGlass Wholesale Orders - Web",
            "Sgc Network Api Client Get Guidelines",
            "Sgc Network Api Heartbeat",
            "Sgc Network Api Parts",
            "Sgc Network Api Parts Kits",
            "Sgc Network Api Parts Moldings",
            "Sgc Network Api Parts Oem",
            "Sgc Network Api Payments Get By Id",
            "Sgc Network Api Referral Get",
            "Sgc Network Api Referral Get Approvals",
            "Sgc Network Api Referral Get By Id",
            "Sgc Network Api Referral Get Diary Notes",
            "Sgc Network Api Referral Get Documents",
            "Sgc Network Api Referral Get Documents By Id",
            "Sgc Network Api Referral Get Invoices",
            "Sgc Network Api Referral Get Parts",
            "Sgc Network Api Referral Get Status Counts",
            "Sgc Network Api Referral Post Approval",
            "Sgc Network Api Referral Post Cancel",
            "Sgc Network Api Referral Post Diary Notes",
            "Sgc Network Api Referral Post Documents",
            "Sgc Network Api Referral Post Invoice",
            "Sgc Network Api Referral Post Redispatch",
            "Sgc Network Api Referral Put Approval",
            "Sgc Network Api Referral Unknown",
            "Sgc Network Api Shop Get",
            "Sgc Network Api Shop Get By Id",
            "Sgc Network Api Shop Get Documents",
            "Sgc Network Api Shop Get Documents By Id",
            "Sgc Network Api Shop Get Parent By Id",
            "Sgc Network Api Shop Patch",
            "Sgc Network Api Shop Post Documents",
            "Sgc Network Api Unknown",
            "Sgc Network Api Users Get",
            "Sgc Network Api Users Get By Id",
            "Sgc Network Api Users Patch By Id",
            "Sgc Network Api Users Post",
            "Sgc Network Api Vehicle Get Lookup",
            "Sgc Network Api Vehicle Get Makes",
            "Sgc Network Api Vehicle Get Models",
            "Sgc Network Api Vehicle Get Styles",
            "Sgc Network Api Vehicle Get Years",
            "Sheboygan Partial Policy Search - Alliance ESL",
            "Sheboygan Policy Search - Alliance ESL",
            "Sheboygan Policy Search ESL",
            "Shelter Claim Registration - Alliance ESL",
            "Shelter Claim Submission - Alliance ESL",
            "Shelter Decrypt Policy Number - Alliance ESL",
            "Shelter Name Search - Alliance ESL",
            "Shelter Name Web Search - Alliance ESL",
            "Shelter Policy Search - Alliance ESL",
            "Shelter Policy Web Search - Alliance ESL",
            "Signing Service Health Check",
            "Southern Mutual Partial Policy Search - Alliance ESL",
            "Southern Mutual Policy Search - Alliance ESL",
            "Southern Mutual Policy Search ESL",
            "Star and Shield Auto Loss - Alliance ESL",
            "Star and Shield Invoice ESL",
            "Star and Shield Name Search - ESL",
            "Star and Shield Name Search Inhouse - Alliance ESL",
            "Star and Shield Policy Search - ESL",
            "Star and Shield Policy Search Inhouse - Alliance ESL",
            "State Auto Name Search ESL",
            "State Auto Name Search LU6.2 ESL",
            "State Auto Name Search Workflow ESL",
            "State Auto Policy Search ESL",
            "State Auto Policy Search LU6.2 ESL",
            "State Farm Glaxis Claim - ESL",
            "State Farm Glaxis Coverage - ESL",
            "State Farm Glaxis Response - ESL",
            "Sublimity Name Search - ESL",
            "Sublimity NameWeb Search - ESL",
            "Sublimity Policy Search - ESL",
            "Sublimity PolicyWeb Search - ESL",
            "Test Transaction",
            "Tower FNOL Auto Loss - Alliance ESL",
            "Tower FNOL General Liability Loss - Alliance ESL",
            "Tower FNOL Property Loss - Alliance ESL",
            "Tower Name Search ESL",
            "Tower Partial Policy Search ESL",
            "Tower Policy Search ESL",
            "Travelers Policy Search - ESL",
            "Trust Guard Claim Registration ESL",
            "Trust Guard Name Search ESL",
            "Trust Guard Policy Search ESL",
            "Twilio Status Search - ESL",
            "UPC Claim Registration - Alliance ESL",
            "UPC Name Search - Alliance ESL",
            "UPC Policy Search - Alliance ESL",
            "UR Router",
            "USAA Claim Registration ESL",
            "USAA HouseHold Search ESL",
            "USAA Name Search ESL",
            "USAA Policy Search ESL",
            "Unique Insurance Auto Loss - Alliance ESL",
            "Unique Insurance Name Search - Alliance ESL",
            "Unique Insurance Policy Search - Alliance ESL",
            "Unique Insurance Reserve Shop - Alliance ESL",
            "Unique Insurance Schedule Shop - Alliance ESL",
            "Unique Insurance Shop List - Alliance ESL",
            "United Heritage Name Search - ESL",
            "United Heritage NameWeb Search - ESL",
            "United Heritage Policy Search - ESL",
            "United Heritage PolicyWeb Search - ESL",
            "Unitrin Name Search",
            "Unitrin Policy Search",
            "Unknown",
            "Utica - CCC MOI - FNOL",
            "Utica Claim Number Gen - FNOL",
            "Utica Name Search - ESL",
            "Utica Name Search - FNOL",
            "Utica Policy Search - ESL",
            "Utica Policy Search - FNOL",
            "Utica Property Name Search - FNOL",
            "Utica Property Policy Search - FNOL",
            "Vermont Mutual Name WEB Search - Alliance ESL",
            "Vermont Mutual Policy WEB Search - Alliance ESL",
            "Vermont Mutual Property Name Search - Alliance ESL",
            "Vermont Mutual Property Policy Search - Alliance ESL",
            "Vermont Mutual Vehicle Name Search - Alliance ESL",
            "Vermont Mutual Vehicle Policy Search - Alliance ESL",
            "Virginia Farm Bureau Auto Loss Claim - FNOL",
            "Virginia Farm Bureau Policy Search - FNOL",
            "Virginia Farm Bureau Property Loss Claim - FNOL",
            "Virginia Policy Locator Member Search - ESL",
            "Virginia Policy Locator Member Search - FNOL",
            "Virginia Policy Locator Name Search - ESL",
            "Virginia Policy Locator Name Search - FNOL",
            "Virginia Policy Locator Policy Search - ESL",
            "Virginia Policy Locator Policy Search - FNOL",
            "Virginia Policy Locator Search - ESL",
            "Virginia PolicyWeb Search - ESL",
            "Wawanesa Name Search - ESL",
            "Wawanesa Policy Search - ESL",
            "West Bend Insurance Claim Registration - ESL",
            "West Bend Insurance Duplicate Search - Alliance ESL",
            "West Bend Insurance Duplicate Search - ESL",
            "West Bend Insurance Invoice - ESL",
            "West Bend Insurance Name Search - Alliance ESL",
            "West Bend Insurance Name Search - ESL",
            "West Bend Insurance Policy Search - Alliance ESL",
            "West Bend Insurance Policy Search - ESL",
            "Westfield Claim Registration Web - Alliance ESL",
            "Westfield Claim Registration Web - ESL",
            "Westfield Name Search - Alliance ESL",
            "Westfield Name Search - ESL",
            "Westfield Name Web Search - Alliance ESL",
            "Westfield Name Web Search - ESL",
            "Westfield Policy Search",
            "Westfield Policy Search - Alliance ESL",
            "Westfield Policy Search - ESL",
            "Westfield Policy Web Search - Alliance ESL",
            "Westfield Policy Web Search - ESL",
            "Westfield Workers Comp Loss - Alliance ESL",
            "Wilson Mutual Policy Search ESL",
            "Work Order Cancellation",
            "Work Order Dispatch - ESL",
            "Work Order Dispatch EDirect Referral Add - ESL",
            "Work Order Dispatch EDirect Referral Cancel - ESL",
            "Work Order Dispatch Health Check - ESL",
            "Work Order Dispatch MainStreet Health Check - ESL",
            "Work Order Dispatch MainStreet Referral Add - ESL",
            "Work Order Dispatch MainStreet Referral Cancel - ESL",
            "Work Order Dispatch Quest Health Check - ESL",
            "Work Order Dispatch Quest Referral Add - ESL",
            "Work Order Dispatch Quest Referral Cancel - ESL",
            "Work Order Dispatch Referral Add - ESL",
            "Work Order Dispatch Referral Cancel - ESL",
            "XYZ Old NI Claim Registration ESL",
            "XYZ Old NI Name Search ESL",
            "XYZ Old NI Policy Search ESL",
            "XYZ-Test Name Search - ESL",
            "XYZ-Test Policy Search - ESL",
            "Zurich Invoice - ESL"
        ];
        vm.clientList = [
            "1st Auto",
            "21st Century Insurance",
            "AIG",
            "ARI Fleet",
            "AS/400",
            "ASI",
            "AUTO CLUB (FL & GA)",
            "Aaa Seagul/WU",
            "Aaa South",
            "Ace Private Risk",
            "Adirondack Insurance",
            "Agri Business",
            "Alfa",
            "Alfa Alliance",
            "Alfa Vision",
            "AllState Motor Club Insurance",
            "Alliance FNOL",
            "Alliance Web Site",
            "Allied",
            "Allstate",
            "Amazon Express",
            "American Family",
            "American Family Connect",
            "Amica",
            "Ariba",
            "Aspen",
            "Austin Mutual",
            "Auto Club Group",
            "Auto Owners Corporation",
            "BES",
            "Berkley One",
            "Bing",
            "Bristol West",
            "Buckeye Insurance",
            "CCCIS",
            "CNA",
            "CSAA",
            "CSE",
            "Central Insurance",
            "Central Mutual",
            "Chubb Canada",
            "Cincinnati Financial",
            "Citizens",
            "Citizens Platinum",
            "ClaimsPro FNOL",
            "Clearcover",
            "Columbia",
            "Commercial LMAM",
            "Commercial LMAM PH Reimbursement",
            "Commercial LMAM-OHIO CASUALTY",
            "Commercial Liberty NorthW",
            "Country Way",
            "CyberSource CreditCard",
            "CyberSource PayPal",
            "Data Warehouse",
            "Database",
            "Donegal",
            "Duncan",
            "ECentral",
            "EDirect",
            "EMC",
            "ESL",
            "Elephant Insurance",
            "Email Store Forward",
            "Emailer",
            "Emkay",
            "Emkay Canada",
            "Encompass Insurance",
            "Energi Insurance",
            "Enterprise ARMS",
            "Enumclaw",
            "Erie",
            "Esurance",
            "Esurance Canada",
            "Exchange Server",
            "Explorer",
            "F5",
            "FCA Company Cars",
            "FEDEX EXPRESS",
            "Farmers",
            "Florida Specialty",
            "Foremost Motorhome",
            "Fremont Insurance",
            "GMAC",
            "Geico",
            "Georgia Farm Bureau",
            "Germania",
            "GlassClaim",
            "Goodville",
            "Grain Dealers",
            "Grange Insurance",
            "Grange Insurance Association",
            "Grange Mutual",
            "Grinnell Insurance",
            "Guardian Insurance",
            "Guide One",
            "Guidewire Internal",
            "HR",
            "Hanover",
            "Hanover Platinum",
            "Hartford",
            "Haulers Insurance",
            "Help Desk / SV 2",
            "Homesite",
            "Horace Mann",
            "Houston General",
            "IMT",
            "IVANS",
            "Idaho Farm Bureau",
            "Indiana Farm Bureau",
            "Indiana Farmers Mutual",
            "Insurance Auto Auctions",
            "Iowa Farm Bureau",
            "Kemper",
            "LMAM",
            "LMAM PH Reimbursement",
            "LMAM-OHIO CASUALTY",
            "Lease Plan",
            "LeasePlan",
            "Legacy Insurance",
            "Liberty",
            "Liberty Mutual",
            "MEEMIC",
            "MID ATLANTIC GROUP AAA",
            "MRM",
            "MainStreet",
            "Maine Mutual Group",
            "Mainframe",
            "Map Wheels",
            "Mapfre",
            "Mendota Insurance",
            "Merchants",
            "Met Life",
            "Metromile",
            "Michigan Insurance",
            "Motorists Group",
            "Motorists Insurance",
            "MsgHub",
            "Mutual Benefit Group",
            "NGIC",
            "NJ Skylands",
            "NJM",
            "Nationwide",
            "North Star",
            "Northern Neck",
            "Ohio Casualty Commercial",
            "Ohio Mutual",
            "Old Kemper Preferred",
            "One Beacon",
            "Oracle",
            "Orbital",
            "PHH",
            "Payment Application HopLite",
            "Payment Application SafeliteHop",
            "Payment Service Status",
            "Payment Service Status Api",
            "Pekin",
            "Pekin Insurance",
            "Peninsula",
            "Penn National",
            "Portage la Prairie Canada",
            "Preferred Mutual",
            "Progressive",
            "Pure Insurance",
            "QBE",
            "Quest",
            "Quincy",
            "Reliant General",
            "Root Insurance",
            "SAG",
            "SAY",
            "SV 2",
            "Safeco",
            "Safelite Api",
            "Safelite Direct",
            "Safelite University",
            "Safelite Website",
            "Safelite.com",
            "Safelite.com UK",
            "Secura Insurance",
            "Security First",
            "Selective",
            "ServiceAutoGlass - Web\n",
            "SgcNetwork",
            "SgcNetwork - Web",
            "SgcNetworkV2",
            "Sheboygan Falls",
            "Shelter",
            "Shelter Insurance",
            "SoapUI",
            "Southern Mutual",
            "Staging table",
            "Star and Shield",
            "State Auto",
            "State Farm",
            "Sublimity",
            "Titan",
            "Total Claim",
            "Tower",
            "Travelers",
            "Trust Guard Insurance",
            "Twilio",
            "UPC",
            "USAA",
            "Unique Insurance",
            "United Heritage",
            "Unitrin",
            "Unknown",
            "Utica",
            "Vermont Mutual",
            "Virginia Farm Bureau",
            "WTS",
            "Wawanesa",
            "Web Service",
            "Websphere MQ",
            "West Bend Insurance",
            "Westfield",
            "Wilson Mutual",
            "XYZ OLD NI",
            "XYZ-Test Insurance",
            "Zurich",
            "test client",
            "test client 2",
            "test client 3"
        ];
        vm.transactionTypeList = [
            "Add Contact",
            "Add Item",
            "Add Service Location",
            "Address Maint",
            "Appointment Query",
            "Appraiser Assignment",
            "Appraiser Search",
            "Assignment",
            "Cali Referral - Load",
            "Callback Request",
            "Check Request",
            "Claim Number Search",
            "Claim Registration",
            "Claim Status",
            "Claim Submission",
            "Client List",
            "ClientId Search",
            "Close Claim",
            "Company Search",
            "Coverage Verification Response",
            "Credit Card Auth ECentral",
            "Credit Card Auth ESL",
            "Credit Card Auth V2 ESL",
            "Credit Card Auth and Settle ESL",
            "Credit Card Auth and Settle V2 ESL",
            "Credit Card Credit ESL",
            "Credit Card Delete Token",
            "Credit Card ECHop ECentral",
            "Credit Card ECHop SV2",
            "Credit Card ECHop Safelite.com",
            "Credit Card ECHop Service Auto Glass",
            "Credit Card ECHop Service Auto Glass 2",
            "Credit Card ECHop Unknown",
            "Credit Card ECHop WTS",
            "Credit Card Find Token ESL",
            "Credit Card Query ESL",
            "Credit Card Register Token ESL",
            "Credit Card Reversal ECentral",
            "Credit Card Reversal ESL",
            "Credit Card SAHop MRM",
            "Credit Card SAHop SV2",
            "Credit Card SAHop Service Auto Glass",
            "Credit Card SAHop Unknown",
            "Credit Card SAHop WTS",
            "Credit Card SGHop ECentral",
            "Credit Card SGHop SV2",
            "Credit Card SGHop Safelite",
            "Credit Card SGHop Service Auto Glass",
            "Credit Card SGHop Service Auto Glass 2",
            "Credit Card SGHop Unknown",
            "Credit Card SGHop Unknown - WPP",
            "Credit Card SGHop WTS",
            "Credit Card Search ESL",
            "Credit Card Settlement ESL",
            "Database Update",
            "Decrypt",
            "Delete",
            "Delivery Time",
            "Department Search",
            "Duplicate Search",
            "EON",
            "Email",
            "Email Store Forward Mailbox Activity.Dev-Failed",
            "Email Store Forward Mailbox Activity.Dev-Inbox",
            "Email Store Forward Mailbox Activity.Dev-Manual",
            "Email Store Forward Mailbox Activity.Sys-Failed",
            "Email Store Forward Mailbox Activity.Sys-Inbox",
            "Email Store Forward Mailbox Activity.Sys-Manual",
            "Email Store Forward Mailbox FnolSub.Dev-Failed",
            "Email Store Forward Mailbox FnolSub.Dev-Inbox",
            "Email Store Forward Mailbox FnolSub.Dev-Manual",
            "Email Store Forward Mailbox FnolSub.Sys-Failed",
            "Email Store Forward Mailbox FnolSub.Sys-Inbox",
            "Email Store Forward Mailbox FnolSub.Sys-Manual",
            "Email Store Forward Mailbox Referral.Dev-Failed",
            "Email Store Forward Mailbox Referral.Dev-Inbox",
            "Email Store Forward Mailbox Referral.Dev-Manual",
            "Email Store Forward SV2 Activity",
            "Email Store Forward SV2 FnolSubmit",
            "Email Store Forward SV2 Referral",
            "Employee Search",
            "Employee Synch",
            "FNOL - Auto Loss",
            "FNOL - General Liability",
            "FNOL - Load",
            "FNOL - Property Loss",
            "FNOL - Workers Comp Loss",
            "FTP Transfer",
            "Farmers FNOL GlassClaim",
            "Fax Request",
            "Fees",
            "GEICO Loss Notification",
            "GMAC Search",
            "Geocode Global",
            "Geocode Reverse",
            "Geocode Zip4",
            "Glaxis Claim",
            "Glaxis Coverage",
            "Glaxis Response",
            "Household Policy Search",
            "Id Search",
            "Instant Payment Notification",
            "Invoice",
            "Market Job Data",
            "Member Number Search",
            "Member Search",
            "Mobile Capacity Query",
            "NAMEFILE Search",
            "Name Search",
            "Notes",
            "Order Return",
            "PO Reciept",
            "POLICYFILE Search",
            "Partial Policy Search",
            "Parts Query",
            "Password Change",
            "Payment Application HopLite GetPaymentApplicationURLs",
            "Payment Application HopLite GetRequiredCyberSourceCreditCardUIFields",
            "Payment Application HopLite GetRequiredFields",
            "Payment Application HopLite GlassTrackTokenPostBack",
            "Payment Application HopLite Ping",
            "Payment Application HopLite TokenPostBack",
            "Payment Application HopLite ValidatePostbackFromCS",
            "Payment Application SafeliteHop CsCreditCard Safelite.com",
            "Payment Application SafeliteHop CsCreditCard Unknown",
            "Payment Application SafeliteHop CsPayPal Safelite.com",
            "Payment Application SafeliteHop CsPayPal Unknown",
            "Payment Application SafeliteHop Safelite.com",
            "Payment Application SafeliteHop Unknown",
            "Payment Service AzAmazonExpress Auth",
            "Payment Service AzAmazonExpress AuthCapture",
            "Payment Service AzAmazonExpress Capture",
            "Payment Service AzAmazonExpress Credit",
            "Payment Service AzAmazonExpress Credit Update",
            "Payment Service AzAmazonExpress OrderInit",
            "Payment Service AzAmazonExpress OrderSetup",
            "Payment Service AzAmazonExpress Query",
            "Payment Service AzAmazonExpress Reversal",
            "Payment Service CsCreditCard Auth",
            "Payment Service CsCreditCard AuthCapture",
            "Payment Service CsCreditCard Capture",
            "Payment Service CsCreditCard CreateToken",
            "Payment Service CsCreditCard Credit",
            "Payment Service CsCreditCard DeleteToken",
            "Payment Service CsCreditCard FindToken",
            "Payment Service CsCreditCard Query",
            "Payment Service CsCreditCard RegToken",
            "Payment Service CsCreditCard Reversal",
            "Payment Service CsCreditCard Search",
            "Payment Service CsCreditCard TokenPurge",
            "Payment Service CsPayPal Auth",
            "Payment Service CsPayPal AuthCapture",
            "Payment Service CsPayPal Capture",
            "Payment Service CsPayPal Credit",
            "Payment Service CsPayPal EcGetDetails",
            "Payment Service CsPayPal EcOrderSetup",
            "Payment Service CsPayPal EcSet",
            "Payment Service CsPayPal Query",
            "Payment Service CsPayPal Reversal",
            "Payment Service Ping",
            "Payment Service Unknown",
            "Pci Payment Service CsCreditCard Auth",
            "Pci Payment Service CsCreditCard AuthCapture",
            "Pci Payment Service Ping",
            "Pci Payment Service Unknown",
            "Peril Search",
            "Phone Search",
            "Ping Search",
            "Policy Detail Search",
            "Policy Details",
            "Policy Locator Member Search",
            "Policy Locator Name Search",
            "Policy Locator Policy Search",
            "Policy Locator Search",
            "Policy Search",
            "Policy Workflow Search",
            "Price Quote Request",
            "Pricing Query",
            "Problem Moulding Questions",
            "Problem Parts Questions",
            "Problem Vehicle Questions",
            "Process Info Inquiry",
            "Promo Query",
            "Receive Text Message",
            "Recommendation",
            "Reference Data Lookup",
            "Referral",
            "Remittance",
            "Reopen Claim",
            "Request Approval",
            "Reserve Shop",
            "SMS Status",
            "Schedule Shop",
            "Scheduling Query",
            "Search",
            "Send Referral",
            "Send Text Message",
            "Service Card Lookup",
            "Shop Search",
            "Status Query",
            "Storage Location",
            "Tax",
            "Token Management",
            "Unknown",
            "Unsolicited Response",
            "Update",
            "Update Claim",
            "Update Mitigation",
            "Update Schedule",
            "User Maintenance",
            "VIN / Service Card lookup",
            "VIN Search",
            "Vehicle Claim Registration",
            "Vehicle Lookup",
            "Vehicle Policy Search",
            "Void Referral",
            "Web-to-web Connection",
            "Wholesale Order",
            "Wholesale Order Update",
            "Work Order Assignment",
            "Work Order Cancellation",
            "Work Order Creation",
            "Work Order Submission",
            "Workers Comp Loss",
            "dummy11",
            "dummy11",
            "test transaction"
        ];

        vm.loading = false;
        // Passed into the tabset directive
        vm.setSearchType = function (searchType) { vm.form.searchType = searchType; };
        // Passed into the tabset directive
        vm.setLookupType = function (lookupType) { vm.form.lookupType = lookupType; };
        // The order in which the transactions appear in the paginated list. Used in the ng-repeat orderBy filter
        vm.transactionSortCriteria = "+transactionTime";
        // Current page of the pagination. Used in the ng-repeat startFrom filter to determine the starting index
        // of the results to display
        vm.currentPage = 0;
        // Whether to display the transaction results as a list or as a count
        vm.resultDisplay = "list";

        // Variable to indicate "include all" for any select element.
        vm.ALL = TransactionQueryBuilderService.symbols.ALL;
        vm.form = {
            accountNumber: "",
            amount: "",
            authorizationCode: "",
            carID: "",
            checkpoint: vm.ALL,
            claimNumber: "",
            client: vm.ALL,
            creditCardNumber: "",
            csr: "",
            ctu: "",
            destination: vm.ALL,
            // Datetime inputs only like the dates to be in this format. Dont care about seconds or milliseconds
            endTime: new Date((new Date()).getFullYear(), (new Date()).getMonth(), (new Date()).getDate(), (new Date()).getHours(), (new Date()).getMinutes(), 0),
            failed: vm.ALL,
            fnolNumber: "",
            genericSearchString: "",
            includeGenericStringInTransaction: true,
            excludeGenericString: false,
            invoiceNumber: "",
            lookupType: "coverage",
            maxTime: "",
            minTime: "",
            orderID: "",
            partNumber: "",
            pingOptions: vm.ALL,
            policyNumber: "",
            process: vm.ALL,
            promoCode: "",
            referralDate: undefined,
            referralNumber: "",
            searchType: "process",
            serverName: "",
            sessionID: "",
            shopNumber: "",
            source: vm.ALL,
            // Datetime inputs only like the dates to be in this format. Dont care about seconds or milliseconds
            startTime: new Date((new Date()).getFullYear(), (new Date()).getMonth(), (new Date()).getDate(), (new Date()).getHours() - 2, (new Date()).getMinutes(), 0),
            subCompany: "",
            transactions: [],
            transactionsPerPage: "250",
            transactionType: vm.ALL,
            warehouseNumber: "",
            workOrderID: "",
            workOrderNumber: "",
            zipCode: ""
        }

        vm.submit = function () {
            vm.loading = true;
            vm.query = TransactionQueryBuilderService.parseToQuery(vm.form);
            TransactionQueryResource.query({ default_operator: "AND", q: vm.query, size: 10000 }).$promise.then(
                function (response) {
                    var transactions = [];
                    angular.forEach(response.hits.hits, function (hit) {
                        var trans = hit._source;
                        trans.transTime = new Date(trans.transTime);
                        if (trans.pingFlag)
                            if (trans.pingFlag === "Y") trans.pingFlag = "Yes";
                            else trans.pingFlag = "No";
                        else trans.pingFlag = "--";
                        if (trans.successful)
                            if (trans.successful === "Y") trans.successful = "Yes";
                            else trans.successful = "No";
                        else trans.successful = "--";

                        transactions.push(hit._source);
                    });
                    vm.form.transactions = transactions;
                    vm.loading = false;
                }, function (error) {
                    console.log("Unable to post form data", error);
                    vm.loading = false;
                });
        };
    }
}());
